export const url = "https://api.themoviedb.org/3/"
export const urlMovie = "https://api.themoviedb.org/3/movie/"
export const urlTv = "https://api.themoviedb.org/3/tv/"
export const urlPerson = "https://api.themoviedb.org/3/person/"
export const key = process.env.KEY
export const keyClient = process.env.NEXT_PUBLIC_KEY
export const imgUrl="https://image.tmdb.org/t/p/"
export const imgOriginal ="original"
export const imgSize = 'w500' 
export const imgSizeW1280 = 'w1280'