import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState , useEffect } from 'react';
import axios from 'axios';

export default function Home() {
  const [list , setList] = useState([])

  async function getPopular (){
    const popular= await axios.get("/api/movies/popular")
      setList(popular.data.results)
  }



useEffect(() => {
    getPopular ()
    return () => {
    
  }
}, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div>
    {list.map((x:any)=>{

      return <div> {x.title}
        </div>
    })}

    </div>
      
    </div>
  )
}
